<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40686" started-at="2018-12-01T06:24:25Z" finished-at="2018-12-01T06:25:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40686" started-at="2018-12-01T06:24:25Z" finished-at="2018-12-01T06:25:06Z">
      <class name="com.technocredits.testscripts.LoginTest">
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="loginTest" duration-ms="10280" started-at="2018-12-01T11:54:25Z" data-provider="ExcelReadForLogin" finished-at="2018-12-01T11:54:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[maulik]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Technocredits]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="loginTest" duration-ms="6667" started-at="2018-12-01T11:54:36Z" data-provider="ExcelReadForLogin" finished-at="2018-12-01T11:54:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[aditya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.technocredits.testscripts.LoginTest.loginTest(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="loginTest" duration-ms="7935" started-at="2018-12-01T11:54:42Z" data-provider="ExcelReadForLogin" finished-at="2018-12-01T11:54:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rahul12]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failed]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="loginTest" duration-ms="7534" started-at="2018-12-01T11:54:50Z" data-provider="ExcelReadForLogin" finished-at="2018-12-01T11:54:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Pravin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Onkar123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failed]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="loginTest" duration-ms="7680" started-at="2018-12-01T11:54:58Z" data-provider="ExcelReadForLogin" finished-at="2018-12-01T11:55:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Vikas]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ankush@Techno]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="afterTest(org.testng.ITestResult)[pri:0, instance:com.technocredits.testscripts.LoginTest@4883b407]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-12-01T11:55:06Z" finished-at="2018-12-01T11:55:06Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1023)
	at org.testng.TestRunner.run(TestRunner.java:628)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.technocredits.testscripts.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
